name: zoidberg
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26
  - tensorflow-gpu
  - notebook=7.2.1
  - pydot=1.4 # for tf.keras.utils.plot_model()
  - pip
  - pip:
    - matplotlib
    - scikit-learn
    - pillow
    - pandas
    - datasets
    - seaborn
    - scikit-image
    - ipympl
    - plotly
    - opencv-python
    - scipy
    - tensorflow~=2.14.0